# Generated by Django 4.2 on 2023-05-06 19:35

import apps.workout.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('number_approaches', models.PositiveIntegerField()),
                ('number_repetitions', models.PositiveIntegerField()),
                ('rest_second', models.PositiveIntegerField()),
                (
                    'day',
                    models.CharField(
                        choices=[
                            ('Mun', 'Monday'),
                            ('Tues', 'Tuesday'),
                            ('Wed', 'Wednesday'),
                            ('Thurs', 'Thursday'),
                            ('Fri', 'Friday'),
                            ('Sat', 'Saturday'),
                            ('Sun', 'Sunday'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=apps.workout.utils.exercise_image_path,
                    ),
                ),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'workout',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercises',
                        to='workout.workout',
                    ),
                ),
            ],
        ),
    ]
