# Generated by Django 4.2 on 2023-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workout_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='day',
            field=models.CharField(
                choices=[
                    ('0', 'Monday'),
                    ('1', 'Tuesday'),
                    ('2', 'Wednesday'),
                    ('3', 'Thursday'),
                    ('4', 'Friday'),
                    ('5', 'Saturday'),
                    ('6', 'Sunday'),
                ],
                max_length=10,
            ),
        ),
    ]
