# Generated by Django 4.2 on 2023-05-05 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('recipient_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('success', 'Success'),
                            ('error', 'Error'),
                        ],
                        max_length=10,
                    ),
                 ),
                (
                    'group_notification',
                    models.CharField(
                        choices=[
                            ('auth', 'Auth'),
                            ('reminder', 'Reminder'),
                        ],
                        max_length=10,
                    ),
                ),
                ('exc_info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
