# Generated by Django 4.2 on 2023-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_html_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group_notification',
            field=models.CharField(
                choices=[
                    ('auth', 'Auth'),
                    ('reminder', 'Reminder'),
                    ('system', 'System'),
                    ('action', 'Action'),
                ],
                max_length=10,
            ),
        ),
    ]
