# Generated by Django 4.2 on 2023-04-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='massage',
            new_name='message',
        ),
    ]
