# Generated by Django 4.2 on 2023-05-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_exercise_day'),
        ('account', '0002_remove_profile_is_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                to='workout.workout',
            ),
        ),
    ]
