# Generated by Django 4.2 on 2023-06-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('workout', '0005_alter_exercise_day'),
        ('history', '0002_alter_workouthistory_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('exercises_title', models.CharField(max_length=255)),
                ('workout_title', models.CharField(max_length=255)),
                ('event', models.ManyToManyField(to='utils.event')),
                (
                    'exercises',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='workout.exercise',
                    ),
                ),
                (
                    'history_workout',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercise_history',
                        to='history.workouthistory',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseApproaches',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_approaches', models.PositiveIntegerField()),
                ('number_repetitions', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'exercise_history',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercise_approaches',
                        to='history.exercisehistory',
                    ),
                ),
            ],
        ),
    ]
