# Generated by Django 4.2 on 2023-06-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'history',
            '0005_rename_close_data_exercisehistory_close_date_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouthistory',
            old_name='data_close',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='workouthistory',
            old_name='data_open',
            new_name='open_date',
        ),
    ]
