# Generated by Django 4.2 on 2023-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        (
            'history',
            '0006_rename_data_close_workouthistory_close_date_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouthistory',
            name='detail_info',
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='event',
            field=models.ManyToManyField(to='utils.event'),
        ),
    ]
