# Generated by Django 4.2 on 2023-06-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_remove_workouthistory_detail_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseapproaches',
            old_name='number_approaches',
            new_name='current_approach',
        ),
    ]
