# Generated by Django 4.2 on 2023-06-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'history',
            ('0008_rename_number_approaches_'
             'exerciseapproaches_current_approach'),
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseApproaches',
            new_name='ExerciseApproach',
        ),
    ]
